### PR TITLE
Just use "Fix Issue"

### PR DESCRIPTION
**Pull request by neonichu**
✨💥✨

### CODE REVIEW

**Comment by JaviSoto** [comment]
Oh man, so much work on this README and the tool, and there's a feature on Xcode that "fixes all issues" 😮🙃

**Comment by dkhamsing** [comment]
:sob:

**Comment by KrauseFx** [comment]
Ha @neonichu is the best again :rocket:

**Comment by haaakon** [comment]
Fix Issue does way more than this project will ever do, it fixes everything!

**Comment by KrauseFx** [comment]
Closed because of merge conflicts :red_circle:

**Comment by neonichu** [comment]
:sob:

**Comment by KrauseFx** [comment]
@neonichu https://github.com/KrauseFx/what-terminal-is-felix-using/pull/1

**Comment by neonichu** [comment]
@KrauseFx you never take my great contributions 😢

**Comment by KrauseFx** [comment]
:cry:

**Pull request closed without merging**
